### PR TITLE
Create 2015-02-03-VaibhavParaashar-HW1

### PR DESCRIPTION
**Pull request by vibe910**

### CODE REVIEW

**Comment by Ecohen4** [comment]
So close!  But all submissions must follow a "Year-Month-Day-YourName-AssignmentName.FileExtension" naming convention. You are missing the .html file extension, which renders this difficult to render/read.

**Comment by vibe910** [comment]
Dr. Cohen,

It is starting to make sense to me now. I didn't realize that uploading
HTML was more important/necessary than the RMD file.

If it helps I would like to push the knitted HTML file on to Git. I don't
want this mistake to result in a loss of credit.

Vaibhav



On Fri, Feb 20, 2015 at 9:50 AM, Ecohen4 <notifications@github.com> wrote:

> Closed #21 <https://github.com/Ecohen4/data-viz/pull/21>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Ecohen4/data-viz/pull/21#event-239159012>.
>



-- 
Vaibhav R. Paraashar
MS in Mechanical Engineering '15
Columbia University

**Comment by Ecohen4** [comment]
Yes, please push the knitted HTML to your origin/master and create a pull
request to ecohen4/master, if you have not already done so.

No worries, no late penalties on the first assignment.
Elliot

On Fri, Feb 20, 2015 at 5:57 PM, vibe910 <notifications@github.com> wrote:

> Dr. Cohen,
>
> It is starting to make sense to me now. I didn't realize that uploading
> HTML was more important/necessary than the RMD file.
>
> If it helps I would like to push the knitted HTML file on to Git. I don't
> want this mistake to result in a loss of credit.
>
> Vaibhav
>
>
>
> On Fri, Feb 20, 2015 at 9:50 AM, Ecohen4 <notifications@github.com> wrote:
>
> > Closed #21 <https://github.com/Ecohen4/data-viz/pull/21>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Ecohen4/data-viz/pull/21#event-239159012>.
> >
>
>
>
> --
> Vaibhav R. Paraashar
> MS in Mechanical Engineering '15
> Columbia University
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Ecohen4/data-viz/pull/21#issuecomment-75335055>.
>



-- 
Elliot Cohen, Ph.D.
Earth Institute <http://www.earth.columbia.edu/articles/view/58> | SEL
<http://sel.columbia.edu/about/> | QMSS
<http://qmss.columbia.edu/faculty-and-staff/>

Columbia University
220 Mudd. Mail Code 4703
500 West 120th Street
New York, NY 10027
+212 854 7993

**Comment by vibe910** [comment]
Prof. Cohen,

It's done. 

Vaibhav

**Pull request closed without merging**
